# Updated from SvelteKit docs. See https://kit.svelte.dev/docs/adapter-static#github-pages for more information

name: Deploy to Vercel

on:
  push:
    branches: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Pulls Vercel token from GitHub secrets
        run: npx vercel --prod --token $VERCEL_TOKEN --yes
    